import { readFile, writeFile } from "node:fs/promises";
import { Script } from "node:vm";

// Bundle this app's two dependency-free modules so file:// previews also work.
// The extension runs the same compiled script; no remote scripts or runtime loader.
const modules = new Map();
for (const name of ["utils", "icons"]) {
  const source = await readFile(new URL(name + ".js", import.meta.url), "utf8");
  const exported = [...source.matchAll(/^export (?:function|const) (\w+)/gm)].map((match) => match[1]);
  if (!exported.length) throw new Error("No exports found in " + name);
  modules.set(name, "const " + name + "Module = (() => {\n" + source.replace(/^export /gm, "") + "\nreturn { " + exported.join(", ") + " };\n})();");
}
let manager = await readFile(new URL("manager.js", import.meta.url), "utf8");
for (const name of modules.keys()) {
  const pattern = new RegExp('import \\{([^}]+)\\} from "\\./' + name + '\\.js";');
  if (!pattern.test(manager)) throw new Error("Missing module import: " + name);
  manager = manager.replace(pattern, (_, names) => "const {" + names + "} = " + name + "Module;");
}
if (/^\s*(import|export)\s/m.test(manager)) throw new Error("Unsupported import/export in manager.js");
const bundle = "// Generated by build.mjs. Edit manager.js, utils.js or icons.js.\n(() => {\n\"use strict\";\n" + [...modules.values()].join("\n") + "\n" + manager + "\n})();\n";
new Script(bundle, { filename: "manager.bundle.js" });
await writeFile(new URL("manager.bundle.js", import.meta.url), bundle);
console.log("Built manager.bundle.js (offline preview + extension)");
